config:
  RequiredTwerkCount: 10 # default: 10
  RangeForShifting: 5 # default: 5
  GrowingParticle: true
  MushroomTreesOnlyOnMycelium: true
  WorkWithPermissions: true
  
  
default:
  Trees:
    Oak: true
    Spruce: true
    Birch: true
    Acacia: true
    Jungle: true
    BigOak: false # developing
    BigSpruce: true
    BigJungle: true
    DarkOak: true
    RedMushroom: true
    BrownMushroom: true
  Crops:
    Wheat: true
    Carrot: true
    Potato: true
    Melon: true
    Pumpkin: true

# do not change
config-version: 2